### ISSUE TITLE
userToken not found error

### ISSUE THREAD

**Issue by kingsj0405** [sookcha/every2cal#1]
I really appreciate this wonderful crawler!
But there's issue while using... so I make this issue and there's chance of pull-request if my time allow.

My environment is as following
- Python 3.7.0b5
- virtualenv on Windows 10

And here's error traceback

```
Traceback (most recent call last):
  File ".\every2cal.py", line 29, in <module>
    xml = e.get_timetable(year, semester)
  File "D:\Dev\Demo\every2cal\everytime.py", line 21, in get_timetable
    token = soup.find(id="userToken")["value"]
TypeError: 'NoneType' object is not subscriptable
```

So I print the soup... but login was successful.

```
<!DOCTYPE html>

<html lang="ko">
<head>
<title>에브리타임</title>
...
<div class="leftside">
<div class="card pconly">
<form class="logged">
<img class="picture" src="https://cf-fpi.everytime.kr/0.png"/>
<p class="nickname">{MY_ID}</p>
<p class="school">{MY_NAME}</p>
<p class="school">{MY_NAME}</p>
<ul class="buttons">
<li><a href="/my">계정 설정</a></li>
<li><a href="/user/logout">로그아웃</a></li>
...
</body>
</html>
```

**Comment by sookcha** [comment]
Thanks for writing this issue. I think the parameter name have changed a bit... maybe. I'll look into it!
