### ISSUE TITLE
에브리타임 세션 발급에 실패하고 있습니다

### ISSUE THREAD

**Issue by mu-hun** [sookcha/every2cal#4]
https://github.com/sookcha/every2cal/blob/2c63de8/everytime.py#L12-L16 에서 403 응답 코드를 받아 [`timetable_result`](https://github.com/sookcha/every2cal/blob/2c63de8/everytime.py#L18) 에서 구문 분석을 하지 못하고 있습니다.

다른 분은 인증 단계가 잘 이뤄지고 있는지 궁금합니다. payload 하드코딩과 urlencoeded 를 시도해보았으나 결과는 같았습니다.

세션을 관리하는 `requests` 모듈의 버전은 레포지토리에 명시한 `2.20.1` 를 사용했습니다.

## 로그 첨부

```
❯ python3 every2cal.py --begin 2021-03-02 --end 2021-06-21
에브리타임 아이디 : 
Password:
가져올 년도 : 2021
가져올 학기 : 1
Traceback (most recent call last):
  File "~/github/sookcha/every2cal/every2cal.py", line 38, in <module>
    main()
  File "~/github/sookcha/every2cal/every2cal.py", line 31, in main
    xml = e.get_timetable(year, semester)
  File "~/github/sookcha/every2cal/everytime.py", line 23, in get_timetable
    tree = ElementTree.fromstring(timetable_result.text)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1348, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by sookcha** [comment]
@x86chi 안녕하세요, 이슈 남겨주셔서 감사합니다. 에브리타임 인증 방식에 변화가 생긴 것 같아요 😢 아마 쉽게 크롤링하지 못하도록 막는 장치를 추가한 모양인데... 확인해보겠습니다. x86chi 님도 한 번 확인해보시고, 혹시 괜찮으시면 PR 주시면 감사하겠습니다 :)

**Comment by brainer3220** [comment]
아래의 **HEADERS**를 추가하면 되긴 합니다만, 서버측에서 이상을 탐지해, ban 먹을수 있습니다.

```python3
self.HEADERS = {
            'Host': 'everytime.kr',
            'Upgrade-Insecure-Requests': '1',
            'Origin': 'https://everytime.kr',
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Whale/2.8.108.15 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'Referer': 'https://everytime.kr/',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7'
        }
```

```python3
  def get_timetable(self, year, semester):
      result_xml = ""

      payload = {'userid': self.userid, 'password': self.password, 'redirect': '/'}
      url = 'https://everytime.kr/user/login'

      with requests.Session() as session:
          login = session.post(url, data=payload, verify=False, headers=self.HEADERS)
          print(login)

          timetable_result = session.post("https://api.everytime.kr/find/timetable/table/list/semester", data={
              "semester": semester,
              "year": year
          }, verify=False, headers=self.HEADERS)
```

**Comment by sookcha** [comment]
에브리타임 사이트 특성 상 크롤링을 민감한 이슈로 보실 것 같은데요. 에브리타임측이 막는 것을 어떻게든 뚫어서 동작하게 할 수는 있겠지만, 일단 그렇게 만들기가 싫었고(찝찝합니다) 언젠가 이 레포가 DMCA Takedown 으로 막힐수도 있고... 이런저런 고민을 좀 했는데요. 에브리타임에 본인 캘린더를 공유할 수 있는 기능이 있더라고요. 그래서 그 기능을 이용해서 .ics 파일로 공유할 수 있도록 프로그램을 수정했습니다. README 도 수정했으니 관심 있으신 분들은 읽어보세요. 감사합니다.
